# Generated by Django 4.2.16 on 2024-11-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='api_key',
            new_name='token',
        ),
        migrations.RemoveField(
            model_name='users',
            name='google_id',
        ),
    ]
