# Generated by Django 4.2.16 on 2024-12-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='fcm_token',
            field=models.CharField(blank=True, null=True),
        ),
    ]
