# Generated by Django 4.2.16 on 2024-12-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_alter_participant_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reports_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
