# Generated by Django 4.2.16 on 2024-12-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField()),
                ('district', models.CharField(max_length=255)),
                ('road_name', models.CharField(blank=True, max_length=255, null=True)),
                ('street_number', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('modified', models.DateTimeField()),
            ],
        ),
    ]
