# Generated by Django 4.2.16 on 2024-11-17 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('puntosdeinteres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nuevo Itinerario', max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favourite', models.BooleanField(default=False)),
                ('arquitectura', models.BooleanField(default=False)),
                ('parques', models.BooleanField(default=False)),
                ('arte', models.BooleanField(default=False)),
                ('compras', models.BooleanField(default=False)),
                ('ocio', models.BooleanField(default=False)),
                ('ocio_nocturno', models.BooleanField(default=False)),
                ('museos', models.BooleanField(default=False)),
                ('manual', models.ManyToManyField(blank=True, related_name='manual_itineraries', to='puntosdeinteres.pointofinterest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='itinerario.itinerario')),
                ('points', models.ManyToManyField(related_name='itinerary_items', to='puntosdeinteres.pointofinterest')),
            ],
        ),
    ]
