# Generated by Django 4.2.16 on 2024-11-24 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerario',
            name='arquitectura',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='arte',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='compras',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='museos',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='ocio',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='ocio_nocturno',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='parques',
        ),
    ]
