# Generated by Django 4.2.16 on 2024-11-26 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerario', '0002_remove_itinerario_arquitectura_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itineraryitem',
            options={'ordering': ['itinerary__id', 'day']},
        ),
    ]
