# Generated by Django 4.2.16 on 2024-12-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntosdeinteres', '0003_pointofinterest_modified_pointofinterest_register_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterest',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
