# Generated by Django 4.2.16 on 2025-01-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntosdeinteres', '0004_alter_pointofinterest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.CharField(default='Usuario desconocido', max_length=150),
            preserve_default=False,
        ),
    ]
