# Generated by Django 4.2.16 on 2024-12-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntosdeinteres', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='register_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
