# Generated by Django 4.2.16 on 2024-11-27 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('puntosdeinteres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PassportPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport_points', to='pasaporte.passport')),
                ('point_of_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport_points', to='puntosdeinteres.pointofinterest')),
            ],
        ),
        migrations.AddField(
            model_name='passport',
            name='points_of_interest',
            field=models.ManyToManyField(related_name='passports', through='pasaporte.PassportPoint', to='puntosdeinteres.pointofinterest'),
        ),
        migrations.AddField(
            model_name='passport',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to=settings.AUTH_USER_MODEL),
        ),
    ]
