# Generated by Django 4.2.16 on 2024-11-18 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
    ]
