# Generated by Django 4.2.16 on 2024-12-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_users_password_alter_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='notifications',
            field=models.BooleanField(default=True),
        ),
    ]
