# Generated by Django 4.2.16 on 2024-12-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_users_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='google',
            field=models.BooleanField(default=False),
        ),
    ]
