# Generated by Django 4.2.16 on 2024-12-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasaporte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passportpoint',
            name='marked_at',
        ),
        migrations.AddField(
            model_name='passportpoint',
            name='is_marked',
            field=models.BooleanField(default=False),
        ),
    ]
